# Task 1:

In [23]:
def div_two_num(a,b):
    try:
        c= a/b
        print(c)
    except Exception as y:
        print(f'Couldn\'t perform the operation as it is a {(y)} error!' )

In [24]:
div_two_num(5,0)

Couldn't perform the operation as it is a division by zero error!


In [27]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

# Using for loop

for s in subjects:
    for v in verbs:
        for o in objects:
            print('{} {} {}.'.format(s,v,o))

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [31]:
# Using list comprehension & for loop

lst = [(s+" "+v+" "+o+'.') for s in subjects for v in verbs for o in objects]

for l in lst:
    print(l)

Americans  play Baseball.
Americans  play Cricket.
Americans  watch Baseball.
Americans  watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

In [29]:
def gen_vandermonde(input_vec,n_col,increasing = False):
    if not increasing:
        output_matrix = np.array([a**(n_col-1-i) for a in input_vec for i in range(n_col)])
        output_matrix = output_matrix.reshape(input_vec.size,n_col)
    elif increasing:
        output_matrix = np.array([a**i for a in input_vec for i in range(n_col)])
        output_matrix = output_matrix.reshape(input_vec.size,n_col)
    return output_matrix

In [31]:
input_vec = np.array([1,2,3,4,5])
n_col     = 5

print('Vandermonde matrix with decreasing order of power:')
print(gen_vandermonde(input_vec,n_col, False))

Vandermonde matrix with decreasing order of power:
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [33]:
print('Vandermonde matrix with increasing order of power:')
print(gen_vandermonde(input_vec,n_col, True))

Vandermonde matrix with increasing order of power:
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]
